---
title: "Analysis"
author: "Sena McCrory"
date: "4/10/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---


## Setup
```{r}
getwd()
library(tidyverse)
library(viridis)
library(sf)
library(scales)
library(nationalparkcolors)
library(trend)
library(nlme)
library(piecewiseSEM)
library(cowplot)
library(zoo)
library(car)
library(dunn.test)

mytilus.metals <- read.csv("./Data/Processed/ICES_Mytilusedulis_Cd_Pb.csv")
mytilus.metals$DATE <- as.Date(mytilus.metals$DATE, format = "%d/%m/%Y")

# theme
my.theme <- theme_minimal(base_size = 14)+
  theme(legend.position = "top")
theme_set(my.theme)
my.colors <- park_palette("CraterLake")[c(5,7,1,2)]


# create separate datasets for lead and cadmium, and filter for just post 1990
mytilus.pb <- mytilus.metals %>%
   filter(PARAM == "Pb" & MYEAR >= 1990)%>%
   droplevels()
mytilus.cd <- mytilus.metals %>%
   filter(PARAM == "Cd"& MYEAR >= 1990)%>%
   droplevels()
mytilus.cd.pb <- rbind(mytilus.cd, mytilus.pb)
summary(mytilus.pb$Value.mgperkg)
summary(mytilus.cd$Value.mgperkg)
# aggregate by monthly median
mytilus.pb.monthly_post1990 <- mytilus.pb%>%
   mutate(Month = format.Date(DATE, format = "%m"))%>%
   group_by(MYEAR,Month)%>%
   dplyr::summarise(Conc = median(Value.mgperkg))%>%
   mutate(Month.Year = paste(MYEAR,Month,"01",sep = ""))
mytilus.pb.monthly_post1990$Month.Year <- as.Date(mytilus.pb.monthly_post1990$Month.Year, format = "%Y%m%d", origin = "1970-01-01")

mytilus.cd.monthly_post1990 <- mytilus.cd%>%
   mutate(Month = format.Date(DATE, format = "%m"))%>%
   group_by(MYEAR,Month)%>%
   dplyr::summarise(Conc = median(Value.mgperkg))%>%
   mutate(Month.Year = paste(MYEAR,Month,"01",sep = ""))
mytilus.cd.monthly_post1990$Month.Year <- as.Date(mytilus.cd.monthly_post1990$Month.Year, format = "%Y%m%d", origin = "1970-01-01")
```

# monthly interpolation

```{r}
# subset and interpolate for after 1990
dim(mytilus.pb.monthly_post1990)
summary(mytilus.pb.monthly_post1990$MYEAR)
12*(2018-1990)-231
105/336 # about 1/3 of the sampling month are missing post 1990...is that okay to interp?

dim(mytilus.cd.monthly_post1990) # still have ~ 1/3 of months missing

```

interpolation for monthly time series analysis
```{r}
# monthly dataset to join
Months <- as.data.frame(seq(as.Date("1990-02-01"),as.Date("2018-12-01"), "month"))
colnames(Months)
Months <- Months %>%
rename(Month.Year = 'seq(as.Date(\"1990-02-01\"), as.Date(\"2018-12-01\"), \"month\")')
class(Months$Month.Year)

# spline interp - results in values < 0... not good
# cd
mytilus.cd.monthly_post1990.interp <- left_join(Months,mytilus.cd.monthly_post1990, by = "Month.Year")
mytilus.cd.monthly_post1990.interp$estimated <- ifelse(is.na(mytilus.cd.monthly_post1990.interp$Conc), 1, 0)
mytilus.cd.monthly_post1990.interp <- mytilus.cd.monthly_post1990.interp%>%
   select(Month.Year, Conc, estimated)
mytilus.cd.monthly_post1990.interp$Conc <- na.spline(mytilus.cd.monthly_post1990.interp$Conc)
# pb
mytilus.pb.monthly_post1990.interp <- left_join(Months,mytilus.pb.monthly_post1990, by = "Month.Year")
mytilus.pb.monthly_post1990.interp$estimated <- ifelse(is.na(mytilus.pb.monthly_post1990.interp$Conc), 1, 0)
mytilus.pb.monthly_post1990.interp <- mytilus.pb.monthly_post1990.interp%>%
   select(Month.Year, Conc, estimated)
mytilus.pb.monthly_post1990.interp$Conc <- na.spline(mytilus.pb.monthly_post1990.interp$Conc)


# linear interp na.approx...better
# cd
mytilus.cd.monthly_post1990.interp2 <- left_join(Months,mytilus.cd.monthly_post1990, by = "Month.Year")
mytilus.cd.monthly_post1990.interp2$estimated <- ifelse(is.na(mytilus.cd.monthly_post1990.interp2$Conc), 1, 0)
mytilus.cd.monthly_post1990.interp2 <- mytilus.cd.monthly_post1990.interp2%>%
   select(Month.Year, Conc, estimated)
mytilus.cd.monthly_post1990.interp2$Conc <- na.approx(mytilus.cd.monthly_post1990.interp2$Conc)
# pb
mytilus.pb.monthly_post1990.interp2 <- left_join(Months,mytilus.pb.monthly_post1990, by = "Month.Year")
mytilus.pb.monthly_post1990.interp2$estimated <- ifelse(is.na(mytilus.pb.monthly_post1990.interp2$Conc), 1, 0)
mytilus.pb.monthly_post1990.interp2 <- mytilus.pb.monthly_post1990.interp2%>%
   select(Month.Year, Conc, estimated)
mytilus.pb.monthly_post1990.interp2$Conc <- na.approx(mytilus.pb.monthly_post1990.interp2$Conc)

mytilus.cd.monthly_post1990.interp2$PARAM <- "Cd"
mytilus.pb.monthly_post1990.interp2$PARAM <- "Pb"

cd.pb.monthly.combined <- rbind(mytilus.cd.monthly_post1990.interp2, mytilus.pb.monthly_post1990.interp2)
```

```{r}
# write csvs of interpolated data
#write.csv(mytilus.cd.monthly_post1990.interp2, "./Data/Processed/cd_monthly_post1990_interp.csv", row.names = FALSE)
#write.csv(mytilus.pb.monthly_post1990.interp2, "./Data/Processed/pb_monthly_post1990_interp.csv", row.names = FALSE)

```

## how have metal concentrations in Mytilus edulis changed over time?

obvious decrease pre 1990, what about 1990 - 2018?
```{r}
# time series trend analysis by month
# cd
cd.monthly.ts <- ts(mytilus.cd.monthly_post1990.interp2$Conc,
                    frequency = 12,
                    start = c(1990,1,1),
                    end = c(2018,12,1))
cd.monthly.ts_trend <- smk.test(cd.monthly.ts)
cd.monthly.ts_trend
summary(cd.monthly.ts_trend) # starts on 1990 Feb, so month 1 is Feb
sea.sens.slope(cd.monthly.ts)

#pb - remove really high outlier? replace with something else?? can't have a missing month
pb.monthly.ts <- ts(mytilus.pb.monthly_post1990.interp2$Conc,
                    frequency = 12,
                    start = c(1990,1,1),
                    end = c(2018,12,1))
pb.monthly.ts_trend <- smk.test(pb.monthly.ts)
pb.monthly.ts_trend
summary(pb.monthly.ts_trend)
sea.sens.slope(pb.monthly.ts)

#heirarchical model - with all sample data post 1990, Country as random effect
#cd
cd.changeovertime.mixed <- lme(data = mytilus.cd,
                               log(Value.mgperkg+1^-40) ~ Country,random = ~1|MYEAR)
summary(cd.changeovertime.mixed)
rsquared(cd.changeovertime.mixed)

cd.changeovertime.fixed <- gls(data = mytilus.cd,
                               log(Value.mgperkg+1^-40) ~ Country)
summary(cd.changeovertime.fixed)
anova(cd.changeovertime.mixed, cd.changeovertime.fixed) # mixed is beter
#pb
pb.changeovertime.mixed <- lme(data = mytilus.pb,
                               log(Value.mgperkg+1) ~ MYEAR,random = ~1|Country)
summary(pb.changeovertime.mixed)
rsquared(pb.changeovertime.mixed)

pb.changeovertime.fixed <- gls(data = mytilus.pb,
                               log(Value.mgperkg+1) ~ MYEAR)
summary(pb.changeovertime.fixed)
anova(pb.changeovertime.mixed, pb.changeovertime.fixed) # mixed is beter


# plot of monthly conc - with interpolated points
ggplot(cd.pb.monthly.combined, aes(x = as.Date(Month.Year), y = Conc, color = PARAM))+
   scale_color_manual(values = my.colors)+
   geom_line()+
   geom_point(aes(shape = as.factor(estimated)))+
   scale_shape_manual(values = c(16,1))+
   facet_wrap(~PARAM, nrow = 2, scales = "free_y")+
   theme(legend.position = "none")+
   labs(x= "Date", y = "Conc of metal (mg/kg wet wt)")

cd.monthly.interp <- ggplot(mytilus.cd.monthly_post1990.interp2, aes(x = as.Date(Month.Year), y = Conc))+
   #geom_line(color = my.colors[1])+
   geom_point(aes(shape = as.factor(estimated)), color = my.colors[1])+
   geom_smooth(method = "lm", se = FALSE, color = my.colors[1])+
   scale_shape_manual(values = c(16,1), labels = c("actual", "interpolated"))+
   #coord_cartesian(ylim=c(0, 10))+
   theme(axis.text.x = element_blank())+
   labs(x= "", y = "Conc of Cd (mg/kg wet wt)", shape = "")+
   guides(shape = guide_legend(override.aes = list(color = "darkgray")))
   #stat_smooth_func(geom="text",method="lm",hjust=0,parse=TRUE) # need outviz package for this
   #scale_shape_discrete(values = c(16,1))
cd.monthly.interp
pb.monthly.interp <- ggplot(subset(mytilus.pb.monthly_post1990.interp2, Conc < 20), aes(x = as.Date(Month.Year), y = Conc))+
   #geom_line(color = my.colors[2])+
   geom_point(aes(shape = as.factor(estimated)), color = my.colors[2])+
   scale_shape_manual(values = c(16,1))+
   geom_smooth(method = "lm", se = FALSE, color = my.colors[2])+
   coord_cartesian(ylim=c(0, 10))+
   theme(legend.position = "none")+
   labs(x= "Date", y = "Conc of Pb (mg/kg wet wt)")
pb.monthly.interp # remove that one really high outlier?? it is pulling the lm
plot_grid(cd.monthly.interp, pb.monthly.interp, nrow = 2)

```


## do concentrations differ by country?
```{r}
country.order.cd <- mytilus.cd %>%
   group_by(Country)%>%
   tally(sort = T, name = "n_bycountry")

country.order.pb <- mytilus.pb%>%
   group_by(Country)%>%
   tally(sort = T, name = "n_bycountry")
# exclude countries with less than 100 samples


# add sample number by country to each df
mytilus.cd <- left_join(mytilus.cd, country.order.cd, by = "Country")
mytilus.pb <- left_join(mytilus.pb, country.order.pb, by = "Country")
mytilus.cd$Country <- reorder(mytilus.cd$Country, mytilus.cd$n_bycountry)
mytilus.pb$Country <- reorder(mytilus.pb$Country, mytilus.pb$n_bycountry)
summary(mytilus.cd$Country)

# filter to remove countries with fewer than 100 samples over the study period
cd.countries <- mytilus.cd %>%
   filter(n_bycountry > 100)%>%
   droplevels()
summary(cd.countries$Country)
pb.countries <- mytilus.pb %>%
   filter(n_bycountry > 100)%>%
   droplevels()
summary(cd.countries$Country)
cd.pb.countries.combined <- rbind(cd.countries, pb.countries)

write.csv(cd.pb.countries.combined, "./Data/Processed/ICES_mytilusedulis_cd_pb_countriesmorethan100.csv", row.names = FALSE)


# non parametric - kruskall wallis
kruskal.test(cd.countries$Value.mgperkg, cd.countries$Country) # distrib are different
dunn.test(cd.countries$Value.mgperkg, g=cd.countries$Country, method = "bh") # all countries are different from each other except for Germany and UK
kruskal.test(pb.countries$Value.mgperkg, pb.countries$Country) # distrib are different
dunn.test(pb.countries$Value.mgperkg, g=pb.countries$Country, method = "bh") # all are diff from each other except for The netherlands and UK, Germany and Ireland, Spain ad Neth, Spain and UK, and UK and NEth

# plot distrib box plots
ggplot(cd.pb.countries.combined, aes(x=Country, y = Value.mgperkg, fill = PARAM))+
   geom_violin(draw_quantiles = .5)+
   scale_y_log10(labels = trans_format("log10", math_format(10^.x)))+
   scale_fill_manual(values = my.colors)+
   facet_wrap(~PARAM, nrow = 2)+
   theme(legend.position = "none")



# plot over time
ggplot(cd.countries %>% arrange(-n_bycountry), 
       aes(x= as.Date(DATE), y = Value.mgperkg, color = Country))+
   geom_point(position = position_dodge(), alpha = .7)+
   scale_color_viridis_d(end = .9, option = "viridis")+
   ylim(0,10)+
   geom_smooth(method = "lm", se = F)

ggplot(pb.countries %>% arrange(-n_bycountry), aes(x= as.Date(DATE), y = Value.mgperkg, color = Country))+
   geom_point(position = position_dodge(), alpha = .7)+
   scale_color_viridis_d(end = .9, option = "inferno")+
   geom_smooth(method = "lm", se = F)+
   coord_cartesian(ylim = c(0,20))
```

```{r}
# two-way ANOVA - assumptions not met
cd.anova <- aov(log(Value.mgperkg+1^-40) ~ as.factor(MYEAR) * Country, data = cd.countries)
summary(cd.anova)
TukeyHSD(cd.anova)
bartlett.test(log(cd.countries$Value.mgperkg+1^-40), g = cd.countries$MYEAR) # unequal variance by year
bartlett.test(log(cd.countries$Value.mgperkg+1^-40), g = cd.countries$Country) # unequal variance by country

#ANCOVA - assumptions not met
ancova.cd <- lm(log(Value.mgperkg+1^-40) ~ MYEAR * Country, 
                data = cd.countries)
summary(ancova.cd)
plot(ancova.cd)
#none of them are normally distributed...
shapiro.test(log(cd.countries$Value.mgperkg[cd.countries$Country == "Germany"]))
shapiro.test(log(cd.countries$Value.mgperkg[cd.countries$Country == "The Netherlands"]))
shapiro.test(log(cd.countries$Value.mgperkg[cd.countries$Country == "Denmark"]))
shapiro.test(log(cd.countries$Value.mgperkg[cd.countries$Country == "Ireland"]))
shapiro.test(log(cd.countries$Value.mgperkg[cd.countries$Country == "United Kingdom"]))
shapiro.test(log(cd.countries$Value.mgperkg[cd.countries$Country == "Norway"]))
lmtest::bptest(ancova.cd) #heteroskedastic, p < 0.001
car::vif(ancova.cd) # due to interaction factor, VIF for country is very high 
outlierTest(ancova.cd) # several problematic outliers


ancova.pb <- lm(log(Value.mgperkg+1^-40) ~ MYEAR * Country, data = pb.countries)
summary(ancova.pb)
plot(ancova.pb)
#none of them are normally distributed...
shapiro.test(log(pb.countries$Value.mgperkg[pb.countries$Country == "Germany"]))
shapiro.test(log(pb.countries$Value.mgperkg[pb.countries$Country == "The Netherlands"]))
shapiro.test(log(pb.countries$Value.mgperkg[pb.countries$Country == "Denmark"]))
shapiro.test(log(pb.countries$Value.mgperkg[pb.countries$Country == "Ireland"]))
shapiro.test(log(pb.countries$Value.mgperkg[pb.countries$Country == "United Kingdom"]))
shapiro.test(log(pb.countries$Value.mgperkg[pb.countries$Country == "Norway"]))
lmtest::bptest(ancova.pb) #heteroskedastic, p < 0.001
car::vif(ancova.pb) # due to interaction factor, VIF for country is very high 
outlierTest(ancova.pb) # several problematic outliers

```

