---
output: 
  pdf_document:
    keep_tex: yes
    fig_caption: yes
    number_sections: yes
geometry: margin=2.54cm
title: "Insert title of project here"
subtitle: "Web address for GitHub repository"
author: "Sena McCrory"
fontsize: 12pt
mainfont: Times New Roman
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
# Set your working directory
getwd()

# Load your packages
#install.packages("sf")
#install.packages("rgdal")
#install.packages("raster")
#install.packages("maps")
library(sf)
library(rgdal)
library(raster)
library(tidyverse)
library(maps)
library(leaflet)
library(mapview)
library(viridis)
library(lubridate)


# Set your ggplot theme
my.theme <- theme_minimal()+
  theme(legend.position = "top")
theme_set(my.theme)

# Load your datasets
ICES_metals.in.biota <- read.csv("./Data/Raw/ContaminantsBiota20202263412jpufqdsst5td1sxozv2woyiz.csv")
table(ICES_metals.in.biota$PARAM)
table(ICES_metals.in.biota$Country)

my.metals <- c("HG", "CD", "PB", "AS", "CR", "CR3+", "CR6+", "CU", "NI", "MN", "FE", "BA")
ICES_my.metals <- ICES_metals.in.biota %>%
  filter(PARAM %in% my.metals)%>%
  droplevels()
table(ICES_my.metals$PARAM)
table(ICES_my.metals$Country)
table(ICES_my.metals$Species)

species.summary <- ICES_my.metals %>%
  group_by(Species)%>%
  tally()
summary(species.summary$n)
top.5.species <- c("Mytilus edulis", "Gadus morhua", "Platichthys flesus", "Clupea harengus", "Limanda limanda")

ices_metals.top5 <- ICES_my.metals%>%
  filter(Species %in% top.5.species)%>%
  filter(MUNIT == "ug/kg")%>%
  droplevels()
#table(ices_metals.top5$MUNIT)
#ices_metals.top5$MYEAR <- as.Date(ices_metals.top5$MYEAR, format = "%Y", origin = "1970-01-01")

ggplot(ices_metals.top5, aes(x=MYEAR, y = Value))+
  geom_point(aes(color = Species), alpha = .5, size = 2, shape = 1)+
  facet_wrap(~PARAM, scales = "free")+
  scale_color_viridis_d(end = .9, option = "magma")
# barium was only measured recently, may be trend for As, diggicult to tell for others due to some high outliers

ices_as <- ices_metals.top5%>%
  filter(PARAM == "AS")%>%
  droplevels()
ggplot(ices_as, aes(x=MYEAR, y = Value))+
  geom_point(aes(color = Species), alpha = .5, size = 2, shape = 1)+
  #ylim(c(0,10000))+
  scale_color_viridis_d(end = .9, option = "magma")+
  facet_wrap(~Species, scales = "free_y")
# gap in clupea harengus monitoring

#Barium
ices_ba <- ices_metals.top5%>%
  filter(PARAM == "BA")%>%
  droplevels()
ggplot(ices_ba, aes(x=MYEAR, y = Value))+
  geom_point(aes(color = Species), alpha = .5, size = 2, shape = 1)+
  #ylim(c(0,10000))+
  scale_color_viridis_d(end = .9, option = "magma")+
  facet_wrap(~Species, scales = "free_y")
# really sparse, eliminate from datasets

#Cadmium
ices_cd <- ices_metals.top5%>%
  filter(PARAM == "CD")%>%
  droplevels()
ggplot(ices_cd, aes(x=MYEAR, y = Value))+
  geom_point(aes(color = Species), alpha = .5, size = 2, shape = 1)+
  #ylim(c(0,10000))+
  scale_color_viridis_d(end = .9, option = "magma")+
  facet_wrap(~Species, scales = "free_y")
#outliers all over the place

#Chromium
ices_cr <- ices_metals.top5%>%
  filter(PARAM == "CR")%>%
  droplevels()
ggplot(ices_cr, aes(x=MYEAR, y = Value))+
  geom_point(aes(color = Species), alpha = .5, size = 2, shape = 1)+
  #ylim(c(0,10000))+
  scale_color_viridis_d(end = .9, option = "magma")+
  facet_wrap(~Species, scales = "free_y")
#good data for mytilus and not much else

# copper
ices_cu <- ices_metals.top5%>%
  filter(PARAM == "CU")%>%
  droplevels()
ggplot(ices_cu, aes(x=MYEAR, y = Value))+
  geom_point(aes(color = Species), alpha = .5, size = 2, shape = 1)+
  #ylim(c(0,10000))+
  scale_color_viridis_d(end = .9, option = "magma")+
  facet_wrap(~Species, scales = "free_y")
#outliers for mytilus

ices_hg <- ices_metals.top5%>%
  filter(PARAM == "HG")%>%
  droplevels()
ggplot(ices_hg, aes(x=MYEAR, y = Value))+
  geom_point(aes(color = Species), alpha = .5, size = 2, shape = 1)+
  #ylim(c(0,10000))+
  scale_color_viridis_d(end = .9, option = "magma")+
  facet_wrap(~Species, scales = "free_y")
# big outliers for mytilus and platichthys

ices_ni <- ices_metals.top5%>%
  filter(PARAM == "NI")%>%
  droplevels()
ggplot(ices_ni, aes(x=MYEAR, y = Value))+
  geom_point(aes(color = Species), alpha = .5, size = 2, shape = 1)+
  #ylim(c(0,10000))+
  scale_color_viridis_d(end = .9, option = "magma")+
  facet_wrap(~Species, scales = "free_y")
#lots of data gaps - maybe remove this one too

ices_pb <- ices_metals.top5%>%
  filter(PARAM == "PB")%>%
  droplevels()
ggplot(ices_pb, aes(x=MYEAR, y = Value))+
  geom_point(aes(color = Species), alpha = .5, size = 2, shape = 1)+
  #ylim(c(0,10000))+
  scale_color_viridis_d(end = .9, option = "magma")+
  facet_wrap(~Species, scales = "free_y")
# outliers for several species may be problematic? 

# perhaps just focus on mytils edulis? and maybe gadus morhua, too if time

```

review of metal concentrations and bioavailability in marine environments
https://scialert.net/fulltextmobile/?doi=jas.2004.1.20



```{r}
str(metals_biota)
summary(metals_biota$MYEAR)
unique(metals_biota$PARAM)

summary(metals_biota$VFLAG) # remove C, D, and S? A means acceptable, assume that nothing means it's okay
summary(metals_biota$BASIS) # is there any way to convert between these??probs not. D - dry wt, L - lipid wt, W - wet weight, what if it doesn't specify anything?
summary(metals_biota$QFLAG) # how to deal with detection limits? there is right censored and left censored data...
summary(metals_biota$MUNIT) # need to convert units after filtering, see what's left

# what about info on what organs/tissues were used? or does this assume it was the whole organisms? not sure on this --- it's the MATRX variable
sort(table(metals_biota$MATRX), decreasing = T)[1:5] # top 3 have a lot more than the rest

# which heavy metals should I look at?? 
my.metals <- c("HG", "CD", "PB", "AS", "CR", "CR3+", "CR6+", "CU", "NI", "MN", "FE", "BA")
# no Fe or Mn in this dataset, possibly because they are considered to be nutrients
my.tissues <- c("LI", "MU", "SB")

metals_biota_filtered <- metals_biota %>%
  filter(PARAM %in% my.metals &         # keep the 8 metals of interest
           VFLAG %in% c("", " ", "A") & # remove data of "suspect" quality
           BASIS == "W" &               # exclude dry wt and lipid wt measurements 
           MATRX %in% my.tissues) %>%   # keep records for top 3 most common tissues
  droplevels()

unique(metals_biota_filtered$PARAM)

metals_biota_filtered$DATE <- as.Date(metals_biota_filtered$DATE, format = "%d/%m/%Y")
class(metals_biota_filtered$DATE)

allmetals <- ggplot(metals_biota_filtered, aes(x=DATE, y = Value))+
  geom_point(aes(color = PARAM), size = .5, alpha = .5)+
  scale_color_viridis_d()+
  geom_smooth(aes(color = PARAM), method = "lm")+
  facet_wrap(~PARAM)

```
## top MATX codes - 
LI - Liver (n=74,688)
MU - muscle (n=58,359)
SB - whole soft body (n=47058)
WO - whole organism (n=1651)
KI - kidney (n=1031)


```{r}
HG <- metals_biota_filtered %>%
  filter(PARAM == "HG")

HGpoints <- st_as_sf(HG, coords = c("Longitude", "Latitude"),  crs=4326)

extent(HGpoints)
crs(HGpoints)



#read in port locations shapefile
ports <- st_read("./Data/SpatialData/ne_50m_ports.shp")
ecoregions <- st_read("./Data/SpatialData/ICES_ecoregions_20171207_erase_ESRI.shp")
mapview(HGpoints, color = "orange")+
  mapview(ports)+
  mapview(ecoregions, color = "blue")


osm.coastlines <- opq (bbox = c(-75,30,55,85)) %>% # c(xmin, ymin, xmax, ymax)
  add_osm_feature("natural", "coastline") %>% 
  osmdata_sf() 


library(geosphere)

distance <- geosphere::dist2Line(p = st_coordinates(HGpoints), 
                         line = 
st_coordinates(osm.coastlines$osm_lines)[,1:2])
```
