---
title: "DataExploration"
author: "Sena McCrory"
date: "4/9/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

## Setup
```{r}
getwd()
library(tidyverse)
library(viridis)
library(sf)
library(scales)
library(nationalparkcolors)
library(lubridate)
library(cowplot)
library(trend)
library(zoo)

mytilus.allyears <- read.csv("./Data/Processed/ICES_Mytilusedulis_Cd_Pb.csv")
mytilus.allyears$DATE <- as.Date(mytilus.allyears$DATE, format = "%d/%m/%Y")

#set theme
my.theme <- theme_minimal(base_size = 14)+
  theme(legend.position = "top")
theme_set(my.theme)
my.colors <- park_palette("CraterLake")[c(5,7,1,2)]

```

```{r}
table(mytilus.allyears$PARAM)

# aggregate by year1979 - 2018
yearly.data <- mytilus.allyears %>%
   group_by(MYEAR, PARAM)%>%
   dplyr::summarise(Conc = median(Value.mgperkg))


#subset post 1990
mytilus.post1990 <- mytilus.allyears%>%
   filter(MYEAR >= 1990)%>%
   droplevels()
table(mytilus.post1990$Country)
table(mytilus.post1990$PARAM)

mytilus.post1990$Country <- factor(mytilus.post1990$Country, levels = 
                                    c("Norway", "United Kingdom", 
                                      "Ireland", "Denmark", "The Netherlands",
                                      "Germany", "Spain", "Belgium", "Iceland", 
                                      "Poland", "Lithuania"))
#mytilus.post1990$Country <- reorder(mytilus.post1990$Country, mytilus.post1990$Value.mgperkg, FUN = median)

# create separate datasets for each contaminant
mytilus.pb <- mytilus.post1990 %>%
   filter(PARAM == "Pb")%>%
   droplevels()
mytilus.cd <- mytilus.post1990 %>%
   filter(PARAM == "Cd")%>%
   droplevels()

# create dataset with out major outliers for display purposes only *********check this, are outliers still there when using post 1990??*************
mytilus.metals.rmoutliers <- mytilus.metals%>%
          filter((PARAM == "Cd" & Value.mgperkg < 30)| 
                    PARAM =="Pb")

# aggregate by month
mytilus.pb.monthly <- mytilus.pb%>%
   mutate(Month = format.Date(DATE, format = "%m"))%>%
   group_by(MYEAR,Month)%>%
   dplyr::summarise(Conc = median(Value.mgperkg))%>%
   mutate(Month.Year = paste(MYEAR,Month,"01",sep = ""))
mytilus.pb.monthly$Month.Year <- as.Date(mytilus.pb.monthly$Month.Year, format = "%Y%m%d", origin = "1970-01-01")
```

## distribution of data

FAO Codex Alimentarius Maximum Level for metals in mussels (bivalves)
Cadmium: 2 mg/kg
lead does not have FAO Maximum Level established

```{r}
# points over time
ggplot(mytilus.post1990, aes(x=as.Date(DATE), y = Value.mgperkg))+
   geom_point(aes(color = PARAM), alpha = .5)+
   scale_color_manual(values = my.colors)+
   scale_y_log10(labels = trans_format("log10", math_format(10^.x)))+
   labs(x= "Date", y = "Log Conc (mg metal/kg wet wt)", color = "Metal")+
   facet_wrap(~PARAM, scales = "free_y", ncol = 1)+
   theme(legend.position = "none")

#histogram
ggplot(mytilus.post1990, aes(x=Value.mgperkg, fill = PARAM))+
   geom_histogram(bins = 40)+
   scale_x_log10(labels = trans_format("log10", math_format(10^.x)))+
   scale_fill_manual(values = my.colors)+
   facet_wrap(~PARAM, scales = "fixed")+
   labs(x="Log Concentration (mg/kg wet wt)", y = "Count", fill = "Metal")+
   theme(legend.position = "none")
#log transform conc
```

## visualization for time series analysis
```{r}
# all data points
ggplot(mytilus.post1990, aes(x=MYEAR, y=1))+
   geom_point()+
   facet_wrap(~PARAM)
summary(mytilus.metals$MYEAR)
# looks like there is data for all four metals for all years between 1979 and 2018

# yearly plot
ggplot(yearly.data, aes(x=MYEAR, y = Conc, color = PARAM))+
   geom_line(size = .8)+
   geom_point()+
   scale_color_manual(values = my.colors)+
   ylim(0,1)+
   facet_wrap(~PARAM, nrow = 2, scales = "fixed")+
   theme(legend.position = "none")+
   labs(x = "Year", y = "Conc (mg metal/kg wet wt)")

# monthly plot
ggplot(mytilus.pb.monthly, aes(x=as.Date(Month.Year), y = 1))+
   geom_point(color = my.colors[2], size = 1)
#looks like there are many months missing for sampling to use monthly data, especially before 1990
```

## by country
```{r}
ggplot(mytilus.post1990, aes(x=Country, fill = PARAM))+
   geom_bar(position = "dodge")+
   scale_fill_manual(values = my.colors)+
   coord_flip()+
   labs(fill = "Metal")
country.count <- mytilus.post1990 %>%
   group_by(PARAM, Country)%>%
   tally()


# violin
ggplot(mytilus.post1990, aes(x=Country, y = Value.mgperkg, fill = PARAM))+
   geom_violin(position = "dodge", scale = "area", draw_quantiles = .5)+
   scale_fill_manual(values = my.colors)+
   scale_y_log10(labels = trans_format("log10", math_format(10^.x)))+
   labs(fill = "Metal")+
   coord_flip()+
   facet_wrap(~PARAM)
   
```



## map of data
```{r}
# data
coastlines_global_wgs84 <- st_read("./Data/SpatialData/GSHHS_shp/l/GSHHS_l_L1.shp")

metal_points_wgs84 <- mytilus.post1990 %>%
  st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326, dim = "XY")
head(metal_points_wgs84)


# check crs - 
st_crs(coastlines_global_wgs84) <- 4326
st_crs(metal_points_wgs84) <- 4326

# create an ocean basemap - looks like ggmap doesn't work for far north coords, cannot reproject :( booooo

```


## create a study sampling area map

```{r}

png("./Output/StudyRegionMap.png", width = 8, height = 10, units = "in", res = 150)
ggplot()+
  geom_sf(data = coastlines_global_wgs84, fill = "lightgray", color = NA, inherit.aes = FALSE)+
  geom_sf(aes(color = PARAM), data = metal_points_wgs84, inherit.aes = F,
          size = 1.2, alpha = 0.5, shape = 18)+ 
  scale_color_manual(values = my.colors) + 
  coord_sf(xlim=c(-25, 32), ylim = c(42, 70), crs = 4326)+
  labs(color = "Mytilus edulis\nsample locations")+
  theme_minimal()+
   theme(strip.text.x = element_text(size = 14),
         legend.position = "none", 
         panel.grid.major = element_blank(), 
         panel.grid.minor = element_blank(),
         panel.border = element_rect(colour = "darkgray", 
                                     fill=NA, size=1))+
   facet_wrap(~PARAM, nrow = 2)
dev.off()

```


# what about detection limits?
```{r}
detectionlimit.summary <- mytilus.post1990 %>%
   group_by(PARAM, DETLI.mgperkg)%>%
   tally()
summary(mytilus.post1990$DETLI.mgperkg[mytilus.post1990$PARAM =="Cd"])
summary(mytilus.post1990$DETLI.mgperkg[mytilus.post1990$PARAM =="Pb"])
write.csv(detectionlimit.summary, "./Data/Processed/DetectionLimitSummary_post1990_cd_pb.csv", row.names = FALSE)
```

